INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('¿Dónde puedo conseguir una conexión a internet?','A on podria conectar-me a internet?','Where can I get an Internet connection?','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('No hablo catalán.','No parlo català.','I do not speak Catalan.','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('Esto no lo entiendo.','No ho entenc.','I do not understand this.','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('¿Habla usted ...?','Parla ...?','Do you speak ...?','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('¿Habla aquí alguien ...?','Algú parla ...?','Does someone talk here ...?','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('inglés','anglès','English','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('Francés','francès','French','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('Por favor, escríbalo.','Si us plau, escrigui-ho.','Please write it.','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('Por favor, repítalo.','Si us plau, repeteixi-ho.','Please repeat it.','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('Un momento, por favor.','Un moment, si us plau.','One moment, please.','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('zero','cero','Zero','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('un','uno','an','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('dos','dos','two','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('tres','tres','three','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('quatre','cuatro','Quatre','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('cinco','cinc','five','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('seis sis','sis','Six sis','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('siete','set','seven','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('ocho vuit','vuit','Eight Vuit','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('nueve nou','nou','Nine Nou','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('diez deu','deu','Ten DEU','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('once onze','onze','Eleven Onze','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('doce','dotze',"twelve o'clock",'INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('trece','tretze','thirteen','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('catorce','catorze','fourteen','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('quince','quinze','fifteen','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('dieziséis ','setze','tenis','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('diecisiete ','disset','seventeen','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('dieciocho','divuit','eighteen','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('diecinueve ','dinou','nineteen','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('veinte','vint','twenty','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('veintiuno vint-i-un','vint-i-un','twenty-one vint-i-un','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('treinta trenta','trenta','thirty thirty','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('cuarenta quaranta','quaranta','forty quaranta','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('cincuenta cinquanta','cinquanta','fifty cinquanta','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('sesenta seixanta','seixanta','sixty Seixanta','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('setenta setanta','setanta','seventy mushroom','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('ochenta','setenta','eighty','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('noventa','vuitanta','ninety','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('cien','noranta','hundred','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('mil mil','cent','thousand thousand','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('un millón','mil','one million','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('un milió','un millón','One thousand','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('un par','un parell','a pair','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('un parell','un par','A Parell','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('saber','saber','to know','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('pensar','pensar','to think','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('venir','venir','come','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('poner','posar','place','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('tomar','agafar','take','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('encontrar','trobar','find','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('escuchar','escoltar','to listen','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('trabajar','treballar','to work','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('hablar','parlar','to talk','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('dar','donar','give','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('gustar','agradar','like','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('ayudar','ajudar','to help','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('amar','estimar','to love','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('llamar','trucar','call','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('esperar','esperar','expect','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('nuevo','nou','new','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('viejo','vell','old','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('pocos','pocs','few','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('muchos','molts','Many','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('incorrecto','incorrecte','incorrect','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('correcto','correcte','Right','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('malo','dolent','evil','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('bueno','bo','well','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('feliz','feliç','happy','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('corto','curt','short','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('largo','llarg','long','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('pequeño','petit','short','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('grande','gran','big','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('allá','allà','there','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('aquí','aquí','here','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('derecha','dreta','right','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('izquierda','esquerra','left','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('hermoso','bonic','handsome','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('joven','jove','young','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('viejo','vell','old','INICI');
INSERT INTO traduccions (IDIOMA_ES, IDIOMA_CAT, IDIOMA_ENG,APARTAT) VALUES ('vale',"d'acord",'OK','INICI');
