/*INSERTS USUARIS_REGISTRATS*/

INSERT INTO usuaris_registrats(usr_username, usr_email, usr_pwd, usr_avatar, usr_registerDate, usr_lastLogin, usr_exp) VALUES ('xXPartyGamer666Xz','pepito2015@gmail.com','123','', '2022-03-15 23:59:59','2022-05-02 13:13:07',5000);
INSERT INTO usuaris_registrats(usr_username, usr_email, usr_pwd, usr_avatar, usr_registerDate, usr_lastLogin, usr_exp) VALUES ('testUser','test@gmail.com','12345', '','2022-01-01 06:35:20','2022-05-02 13:10:37',2300);
INSERT INTO usuaris_registrats(usr_username, usr_email, usr_pwd, usr_avatar, usr_registerDate, usr_lastLogin, usr_exp) VALUES ('testUser2','test2@gmail.com','12345','','2022-04-27 10:06:50','2022-05-02 13:13:46',560);
INSERT INTO usuaris_registrats(usr_username, usr_email, usr_pwd, usr_avatar, usr_registerDate, usr_lastLogin, usr_exp) VALUES ('testUser3','test3@gmail.com','abcde','', '2022-04-15 23:59:59','2022-05-02 13:13:07',1780);


/*INSERTS CATEGORIES*/

INSERT INTO categories(ID, cat_nom, cat_desc) VALUES (1,'PELIS Y SERIES','En esta categoria habrán preguntas sobre actores, directores y personajes relacionados con el mundo del cine y de las series ');
INSERT INTO categories(ID, cat_nom, cat_desc) VALUES (2,'AUTOMOVILES','En esta categoria habrán preguntas sobre automoviles y motor');
INSERT INTO categories(ID, cat_nom, cat_desc) VALUES (3,'DEPORTES','En esta categoria habrán preguntas sobre el mundo del deporte');
INSERT INTO categories(ID, cat_nom, cat_desc) VALUES (4,'ARTE Y LITERATURA','En esta categoria habrán preguntas sobre arte y literatura');
INSERT INTO categories(ID, cat_nom, cat_desc) VALUES (5,'CIENCIA Y NATURALEZA','En esta categoria habrán preguntas sobre curiosidades sobre la Ciencia y la Naturaleza');
INSERT INTO categories(ID, cat_nom, cat_desc) VALUES (6,'MUSICA','En esta categoria habrán preguntas sobre diferentes cantantes y obras.');


/*INSERTS PREGUNTES_RESPOSTES*/

INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'¿Que Any es considera el Jazz com musica?','https://okdiario.com/img/2018/10/29/pasos-jazz.jpeg');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (2,'¿Quins van ser els primers cotxes que va fer Ford?','https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.3djake.es%2Frevell%2Fmodelo-1913-ford-model-t-road&psig=AOvVaw2HTwLuP8rgZGjEs4whV815&ust=1651054739017000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCPiv283AsfcCFQAAAAAdAAAAABAD');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quien era Federico Garcia Lorca?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Que pasaria si chutas una pelota a la velocidad de la luz?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'Com es diu el personatge que surt a la foto?','https://static.wikia.nocookie.net/tomyjerry/images/e/ee/Tom_%28gato%29.png/revision/latest/scale-to-width-down/180?cb=20141026114040&path-prefix=es');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'De qui és la canço amb la lletra "Te quiero ride como mi bike"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿De qué película es este personaje?','https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2018/05/30/15276918010543.jpg');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quien es el autor de esta obra?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'A qui es considera com el rei del rock?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Que falta entre los arcos del Coliseo Romano?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,"Como se llama el company de Tom clancy's Jack Rayan ?",'');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿De quien trata la película "La teoría del todo"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿ A que libro infantil de la saga de Harry Potter pertenece el cuento "La fábula de los tres hermanos"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Como se llama el phsicologo de la pelicula Jolt ?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Con las matematicas actuales se puede calcular la densidad de un agujero negro?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'¿Cual és el deporte electrònico mas competitivo del mundo?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quien era "Halston"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,"¿A quien pertenece la canción don't go breaking my heart?",'');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'Com continua la següent cançó ? "Last Christmas, I gave you my..."','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cuanto mide el universo observable hasta la fecha?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (2,'¿Quin es un dels super cotxes mes rapids del mon?','https://thumbs.dreamstime.com/b/koenigsegg-jesko-ginebra-suiza-de-marzo-el-modelo-la-preproducci%C3%B3n-del-supercar-present%C3%B3-en-sal%C3%B3n-autom%C3%B3vil-internacional-143060616.jpg');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'E=mc2 es una fórmula incluida en una teoría científica. ¿Cuál?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'Quina banda anglesa és considera com la millor de tots els temps?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quién es el autor de la Ilíada y la Odisea?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'Quin és el llibre més venut del món?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cual es el pez mas inutil del mundo?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quien de estas personas es una autora feminista del siglo XVII?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,"Qui és l'home de la foto?",'https://static-abcblogs.abc.es/wp-content/uploads/sites/250/2019/12/sinatra-516x315.jpg');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'A quin element químic es refereix el símbol Ag?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'Com es diu aquesta canço?','https://hips.hearstapps.com/es.h-cdn.co/hares/images/cultura/ocio/michael-jackson-thriller-video/2711550-1-esl-ES/thriller-el-videoclip-que-lo-cambio-todo.jpg');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Que acción realizan las amantis religiosas durante el coito?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Quien es el autor del "Quijote"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'Quina es la pel·lícula amb més ventes de la història ?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿De que época son realmente las melodías de "Los bridgerton"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿En que lugar se situa la famosa estátua de "Eros y Psique o Psique y cupído"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'El Episkyros es una de las primeras formas de un deporte. ¿Cuál?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿De que tratan los comics de "Joe Bar team"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cual fue la bomba cuyo unico impedimento de que explotara, era un destornillador?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,"Com es diu la pelicula que surt a l'imatge?",'');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'Quin artista o grup musical té el record de visites en 24h a youtube?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'Quants punts suma un tir lliure a basquet?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'Quina es la cançó més escoltada de la història','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,"Quants jugadors de camp hi ha en l'handbol?",'');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'Quin ha sigut el fichatge més car de la història del futbol ?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿En que ciudad se situa el museo "Guggenheim"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'¿En que deporte se realiza la postura del "Gato Vaca"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'Cual de los siguentes personajes es un científico?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Como se llama la actriz que interpreta "Maléfica"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Cual de estas películas protagoiza Anne Hathaway?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿En que Lugar están situadas las ruinas de el Partenón?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'¿Cual de las siguientes respuestas hace referència a una penalización en un campeonato de rítmica?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'¿Cual de estos objetos es usual en bailes de rítmica?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cual es el animal más grande del mundo?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cuanto dura la vida de una mosca?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'¿Que tipo de terreno manejan las motos de motocross?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Cuantas películas tiene la saga del señor de los anillos?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quien fue Julius Caesar?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,"Persona més jove en guanyar el millor album de l'any",'');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'¿A quien pertenece la 5ta sinfonía?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (6,'¿Cual es el nombre real de Bad Bunnny?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cual es la famosa formula de Einstein que aportó a la creacion de la bomba atómica?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'Qui té el rècord de major velocitat aconseguida a peu durant un event esportiu ?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (2,'¿Quan es va crear el primer motor de combustio?','https://www.google.com/url?sa=i&url=https%3A%2F%2Fes.wikipedia.org%2Fwiki%2FHistoria_del_motor_de_combusti%25C3%25B3n_interna&psig=AOvVaw33E3lhniKrYbFhcAYsVnTF&ust=1651054879495000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCOC2k_PAsfcCFQAAAAAdAAAAABAD');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Cual de estas películas está basda en un libro?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (2,'¿Qui va disenyar el primer automobil?','https://www.google.com/url?sa=i&url=https%3A%2F%2Fes.wikipedia.org%2Fwiki%2FCarl_Benz&psig=AOvVaw3QV_8yU4cyWu238V4l2osB&ust=1651055003910000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCLjKuLDBsfcCFQAAAAAdAAAAABAV');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (2,'¿Quants caballs de potencia te un Bugatti Veyron?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿De que color es la sangre del cangrejo erradura?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿A quien pertenece el cuadro de "El sol naciente"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (2,'¿Quina es la velocitat punta del Hennessey venom gt?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿A quien pertenece el cuadro "Noche Estrellada"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (2,'¿Que es la rueda donut?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cuantos Kilómetros por hora puede alcanzar una chita adulto?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Que le pasa al protagonista de Breaking Bad?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Cuantas temporadas tiene "Anatomía de Grey"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Que dos actores protagonizan la película de Moulin Rouge?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cuantas neuronas tiene un cerebro adulto?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cuanto cuesta un cerebro humano?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quien construyó la Torre Eiffel?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Cual de estas series está basada en personas reales?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Quien protagoniza Pretty Woman?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Cuantos oscars consiguió "La lista de Schiendleer"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Quien protagonizó "El zorro"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Quien dirigió "El lobo de Wall Street"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Cuantos libros tiene "Geronimo Stilton?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Cual de las opciones pertenece a la mitología griega?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cada cuanto tiempo tiene la menstrución de un perro?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (5,'¿Cual de estas opciones no pertenece a la tabla periodica?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'¿Quien es el mejor nadador/a de todos los tiempos?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quien era Virginia Wolf?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Cuál es el tema principal de "La Naranja Mecánica"?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿Quien era Friederich Nietzsche?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (3,'¿Cuando se jugó el primer partido de baloncesto?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (1,'¿Que película protagonza Robin Williams?','');
INSERT INTO preguntes (categoria_id, preg_pregunta, preg_img) VALUES (4,'¿ De que trata realmete el famoso cuento de "La caperucita Roja"','');

INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Als Anys 1920 en Estats units i als 1950 en Europa i Japo','','','',1);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Ford Model T','Volkwagen','Chevrolet','Gready',2);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Poeta y dramaturgo de mayor influencia en el siglo XX','Un doctor muy reconocido de su época','El mejor Bailarín de Salsa del siglo XX','Director de cine Italiano',3);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Las particulas en el aire no tendrian tiempo de apartarse,causando una explosion nuclear en base a la energia ejercida por el chute, debastando todo a tu alrrededor','Que chutas mas rapido','Que viajarias en el tiempo','Me quedo sin pierna',4);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Tom','Tim','Toad','Tin',5);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Rosalia','Bob Dylan','Bad Bunny','Nicki Nicole',6);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Super Mario Bros','Donkey Kong','Ben-Hur','La Pasión de Cristo',7);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Salvador Dalí','Liza Minnelli','Picasso','Antonio Banderas',8);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Elvis Presley','Michael Jackson','John Lennon','Chuck Berry',9);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Estatuas de mármol','Nada, estaban igual que en la actualidad, vacios','Árboles','Cestas de escudos y lanzas',10);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('James Greer','','','',11);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Stephen Hawking','','','',12);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Cuentos de Beedle el Bardo','Quiddich','Animales fantásticos y donde encontrarlos','Cuentos a media noche',13);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Dr.ivan Munchin','','','',14);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('No, por el momento al no poderse efectuar calculos sobre su densidad, se considera en si infinita/incalculable','','','',15);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('League of Legends','Valorant','Free Fire','Counter Strike',16);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Diseñador de moda estadounidense','Escritor estadounidense','Un bombero muy reconocido del Amazonas','Modelo Francés',17);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Elton john','George Michael','Lil Nas','Steven Spielberg',18);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Heart','Cart','Art','Start',19);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('93,016 miles de millones años luz','890,019 millones de años','Desconocido hasta la fecha','9,890,000 mil millones de años luz',20);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Koenigsegg Jesko','Bugatti veyron super sport','McLaren senna','Ferrari FXX K Evo',21);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('La teoría de la relatividad de Einstein','La teoría del Big Bang','La teoría de la Evolución','El principio de incertidumbre de Heisenberg',22);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Queen','Pink Floyd',"Guns N' Roses",'Red Hot chilli peppers',23);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Homero','Marge','Bart','Lisa',24);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('La Biblia','Don Quixot','Las mil y una noches','After',25);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('El pez luna','El pez payaso','La sardina','El pez gato',26);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Jane Austen','Lana del Rey','Agatha Christie','J.K.Rowling',27);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Frank Sinatra','Louis Armstrong','Elton John','Jonny Cash',28);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Plata','Or','Argent','Plom',29);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Thirller','Walking dead playlist','Toxicity','Billie Jean',30);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Comerse la cabeza del macho','Intentar escapar','Volar durante el coito','Llamar la atención de otros machos',31);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Miguel de Cervantes','Joan Vinyoli','La Reina Isabel de Inglaterra','Garcilaso de la Vega',32);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Avatar','Shrek 2','Avengers : Endgame','Pesadilla antes de Navidad',33);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Del siglo XXI','En el siglo XVIII','En el siglo V','IV',34);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('En Louvre','En el museo Guggenheim','Museo de Barcelona "MNAC"','Museo Vaticano',35);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Fútbol','Baloncesto','Balonmano','Moto GP',36);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Tratan sobre la jerga, la vida y costumbres de los moteros.','Sobre la jerga y la vida juvenil','Sobre la vida y las costumbres de otros paises','Sobre la jerga y la vida de las personas mayores',37);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Núcleo del Demonio','Bomba de hiroshima','TSAR bomba','Misil GBU-34',38);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Et','Las bicicletas son para el verano','Kiki aprendiz de bruja','Las mil y una noches',39);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('"Butter" de BTS','"Con altura" Rosalia','"How you like that" Black Pink','"Gasolina" Daddy Yankee',40);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('1','2','3','4',41);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Baby Shark','Gangnam style - PSY','Despacito - Luis Fonsi','Shape of you - Ed Sheeran',42);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('7','6','5','8',43);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Neymar Jr','Cristiano Ronaldo','Lionel Messi','Andrés Iniesta',44);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Bilbao','Duseldorf','Orleans','Málaga',45);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Yoga','Pilates','Ballet','RPG',46);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Gregor Mendel','Georges Moustaki','George MacKay','George Mallory',47);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Angelina Jolie','Jennifer Aniston','Emma Stone','',48);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('El diablo viste de prada','Cinco hermanos','Sexo en nueva york','Entre dos mundos',49);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Atenas, Grecia','Roma, Italia','Barcelona, España','Nueva York, América',50);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Salir de los límites establecidos en la moqueta de baile','Llevar un mayot que sea blanco.','Bailar con una pelota','Llevar las uñas pintadas de negro',51);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Mazas','Silla','Raqueta','Pelotas de tennis',52);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('La ballena azúl antártica','El tiburón blanco','El elefante','La orca',53);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('28 días','15 días','5 días','1 año',54);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Se realiza en circuitos de tierra','Circuitos de hormigón','Por la montaña','En un circuito de carretera',55);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('3','4','8','2',56);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Dictador Romano','Un escritor del siglo XVII','El pionero de la obra teatral griega','Padre de Sócrates',57);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Billie Ellish','Olivia Rodrigo','Beyonce','The Weeknd',58);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Beethoven','Mozart','Yiruma','Chopin',59);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Benito Antonio Martínez Ocasio','Barni Benito Antonio','Sebastian de la Rosa','Ángel Benito Reyes',60);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('E=mc²','v = Δs/Δt','C= π*d / 2*π*r','u = u (x1, x2, x3; t)',61);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Usain Bolt','Gareth Bale','Toni Bou','Stephen Curry',62);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Any 1915','Any 1935','Any 2000','Any 2002',63);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('El corredor del laberinto','Dando la nota','Sr y Sra Smith','Un pequeño favor',64);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Nicolas Joseph Cugnot','Nicola Tesla','Lewis Hamylton','Frenando Afondo',65);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('1200CV','1000CV','2010CV','102CV',66);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Azul','Roja','Verde','Morada',67);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Monet','Picasso','Frida Kalo','Jackson Pollock',68);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('278KM/H','268KM/H','509KM/H','306KM/H',69);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Vincent van Gogh','Joan Miró','Francisco de Goya','Banksy',70);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('la rueda temporal','Ruedines','la rueda oreo','la rueda trueno',71);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('112 y 120 km/h','200 km/h','140 y 150 km/h','90 km/h',72);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Tiene cancer','le gusta lo q le encanta','Es amigo de Toni Bou','tiene fimosis',73);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('18 temporadas','12 temporadas','9 temporadas','10 temporadas',74);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Ewan McGregor y Nicole Kidman','Angelina Jolie y Johnny depp','Rayan Gosling y Rachel Adams','Brad Pitt y Claire Forlani',75);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('100.000 millones de neuronas','12.000 millones de neuronas','700.000 billones de neuronas','10 neuronas y en decadencia',76);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('1200','30','1.000 millones','Gratis',77);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Gustave Eiffel','Pierre Eiffel','Pierre Lescot','Louis Le Vau',78);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Peaky Blinders','TVD','Lost','Lupin',79);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Richard Gere','Robbin Williams','Nicholas Cage','Keanu Reeves',80);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('7','0','3','4',81);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Antonio Banderas','Miguel Ángel Silvestre','Benito Poecino','Javier Bardem',82);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Martin Scorsese','Pedro Almodovar','Tim Burton','Woody Allen',83);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('253','100','87','335',84);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Edipo Rey','Thor','Isis y los siete escorpiones','La divinidad de Aspasio',85);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Cada 7 u 8 meses o incluso una vez al año','1 vez al mes como a las mujeres','cada 5 o 6 meses o 2 veces al año','Solamete cada 3 meses',86);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Pv','Cd','Po','C',87);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Michael Phelps','Alexandr Popov','Mireia Belmonte','Eric Moussambani',88);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Escritoa','Escultora','Arquitecta','Actriz',89);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Sátira social','La mente asesina','El comportamiento de los jovenes','De la influencia musical',90);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Filósofo','Piloto','Escritor de novelas Románticas','Profesor de programación',91);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('1892','1800','1863','1912',92);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('Hook','Noche en el museo','Niños grandes','A todo gas',93);
INSERT INTO respostes (resp_correcte, resp_incorrecte_1, resp_incorrecte_2, resp_incorrecte_3, preg_id) VALUES ('','','','',94);

